# Generated by Django 3.1.7 on 2021-04-29 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='email_id',
            field=models.CharField(max_length=30),
        ),
    ]
